### ISSUE TITLE
How to install and convert?

### ISSUE THREAD

**Issue by mununki** [godot-extended-libraries/lottie#9]
I’m new to Godot and don’t know well the tooling. I couldn’t find any instruction or guide to install and convert lottie files. Can you give me a hit?

**Comment by fire** [comment]
I'll need to merge in a way to make release so you can download a 3.4 build.

Need to clear my backlog, so I don't know when I'll get to this.

The base idea is to put the module in the godot engine modules folder and build.

**Comment by mununki** [comment]
Great to hear that this feature will be released in Godot. I can't wait!
Actually, it would be very helpful and great to use this lib to convert my lottie jsons for my project which has a running deadline. Any chance to try it before release?

Just put this lib inside modules directory in godot source, and build?

**Comment by fire** [comment]
Ah, sorry as a fork. I wasn’t clear. Yes.

**Comment by mununki** [comment]
@fire I've tried to build the master branch of godot with this lib which is put in `/modules` directory of godot source. I've cloned this repo in `/modules`. But I face this error, can you advise me of how to fix?

```
In file included from modules/lottie/register_types.cpp:33:
modules/lottie/resource_importer_lottie.h:35:10: fatal error: 'scene/3d/mesh_instance.h' file not found
#include "scene/3d/mesh_instance.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from modules/lottie/resource_importer_lottie.cpp:31:
modules/lottie/resource_importer_lottie.h:35:10: fatal error: 'scene/3d/mesh_instance.h' file not found
#include "scene/3d/mesh_instance.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
scons: *** [modules/lottie/register_types.osx.tools.arm64.o] Error 1
1 error generated.
scons: *** [modules/lottie/resource_importer_lottie.osx.tools.arm64.o] Error 1
scons: building terminated because of errors.
```

**Comment by fire** [comment]
I was not aware that Godot 4 is ready to use yet. Are you sure?

**Comment by mununki** [comment]
Oh! I thought that `main` branch is the latest official release version v3.4. Is it v4?

I tried to compile the `main` branch of godot, and compiling was successful without the lottie lib. I faced the  above error when I tried to compile the godot source with this lottie lib in `/modules` directory in source.

**Comment by mununki** [comment]
I downloaded the source code zip file of godot stable v3.4. The initial compilation was successful, then I tried to compile with this lib then I got this error. Can you give me a tip to resolve this? I don't have an experience of clang tooling.

```
[ 82%] Linking Program        ==> bin/godot.osx.tools.arm64
[ 99%] Building compilation database compile_commands.json
[100%] progress_finish(["progress_finish"], [])
[100%] Undefined symbols for architecture arm64:
  "_pixman_composite_over_n_8888_asm_neon", referenced from:
      color_SourceOver(unsigned int*, int, unsigned int, unsigned int) in libmodules.osx.tools.arm64.a(vdrawhelper_neon.osx.tools.arm64.o)
  "_pixman_composite_src_n_8888_asm_neon", referenced from:
      memfill32(unsigned int*, unsigned int, int) in libmodules.osx.tools.arm64.a(vdrawhelper_neon.osx.tools.arm64.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/godot.osx.tools.arm64] Error 1
scons: building terminated because of errors.
```

compile command was `scons platform=osx arch=arm64 --jobs=$(sysctl -n hw.logicalcpu)` on Apple M1

**Comment by fire** [comment]
I am making a build on the Github actions. https://github.com/godot-extended-libraries/lottie. Will report back.

**Comment by mununki** [comment]
OMG!!! I downloaded the artifact from https://github.com/godot-extended-libraries/lottie/actions/runs/1446382768. It works!!! It is FANTASTIC!

Really appreciate your help. I hope to have this feature in the next stable release of Godot soon.
![image](https://user-images.githubusercontent.com/36963424/141217408-b8c38c67-cb5e-4735-8b3c-5f57ef7b0946.png)

**Comment by mununki** [comment]
As far as I know, in order to export the project, the export template is needed. Can I use the existing export template of v3.4? or should I compile for the export template per each platform as you've done with github actions?

**Comment by fire** [comment]
I think you need to use the export template for every platform. (outdated)

I think it bakes the result of lottie. So it doesn't require lottie on runtime though.

Take care about animation and compression. Compression using scn zstd compression is significant.

**Comment by mununki** [comment]
It sounds good. But I'm not sure it bakes the loader for json. I imported the lottie json and saved the project, then I loaded the project and tried to export it for windows in the stable v3.4 godot(I checked the imported json as AnimatedSprite). Then I ran the exported executable on windows. I saw this errors. I guess I should compile the export template for v3.4.1-rc as you've done with github actions. Am I right on track? if so, I'll fork this repo and add another github action script to compile the export template for v3.4.1-rc

```
ERROR: No loader found for resource: res:// _Render.json.
   At: core/io/resource_loader.cpp:290
ERROR: poll: res://src/Screens/MainScreen.tscn:8 - Parse Error: [ext_resource] referenced nonexistent resource at: res:// _Render.json
   At: scene/resources/resource_format_text.cpp:440
ERROR: Failed to load resource 'res://src/Screens/MainScreen.tscn'.
   At: core/io/resource_loader.cpp:212
ERROR: Failed loading resource: res://src/Screens/MainScreen.tscn. Make sure resources have been imported by opening the project in the editor at least once.
   At: core/io/resource_loader.cpp:282
ERROR: Failed loading scene: res://src/Screens/MainScreen.tscn
   At: main/main.cpp:1961
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450
ERROR: There are still MemoryPool allocs in use at exit!
   At: core/pool_vector.cpp:66
```

**Comment by mununki** [comment]
I've compiled the export templates for windows and I verified that the exported executable binary is running and the json AnimateSprite is working on windows! It's GREAT!!!

![image](https://user-images.githubusercontent.com/36963424/141241252-0892d043-7b26-439a-bf03-38b85c7e3adf.png)

**Comment by mununki** [comment]
@fire I'm truly sorry for disturbing you. Finally, I tried to compile the javascript export template but no gain. Can you check my github action script to fix?

https://github.com/mattdamon108/lottie/blob/master/.github/workflows/javascript.yml

**Comment by fire** [comment]
The log mentions ustring in core godot engine.

**Comment by fire** [comment]
I think its “ warnings=extra  “ causing trouble.

**Comment by fire** [comment]
Leave me a note how you’re using this!

**Comment by mununki** [comment]
What I'm trying to do is exporting my project to HTML5. As far as I guess, I need the javascript export template for v3.4.1-rc in order to export my project to HTML5. So I'm following the [doc](https://docs.godotengine.org/ko/stable/development/compiling/compiling_for_web.html#building-export-templates) and trying to compile it and use it in this project export setting after putting the compiled zip files(`webassemply_release.zip`, `webassembly_debug.zip`) in templates directory.
![image](https://user-images.githubusercontent.com/36963424/141260967-525b50e3-ecde-4327-babb-2077925884b7.png)

**Comment by fire** [comment]
Put it in debug and release (custom template)

**Comment by mununki** [comment]
I put it in debug and release in custom template, and encounter this error pops.

![image](https://user-images.githubusercontent.com/36963424/141262381-22832880-0702-444b-9676-6766c3766a80.png)

**Comment by mununki** [comment]
This is an debug log in console.
![image](https://user-images.githubusercontent.com/36963424/141264432-067e7272-529a-4458-a054-608f451c3f12.png)

**Comment by mununki** [comment]
I found this [doc](https://docs.godotengine.org/ko/stable/tutorials/platform/customizing_html5_shell.html#custom-html-page-for-web-export), I put default `export_page.html` in Custom Html Shell in setting. The error is gone. But when I open the .HTML file, it shows nothing. It seems reference to `.js` but there's no `.js` and `.wasm` file in export destination directory.

![image](https://user-images.githubusercontent.com/36963424/141268355-f3f4f120-355b-4817-ad47-f38bc7f06fbd.png)

![image](https://user-images.githubusercontent.com/36963424/141268170-d81769b6-c308-4ecf-b7c0-15faddbc5ea8.png)

![image](https://user-images.githubusercontent.com/36963424/141268210-38ffadcf-dfdb-4831-bf6e-3e805a034417.png)

**Comment by fire** [comment]
Use the preview server. Its one of the launch buttons.

**Comment by mununki** [comment]
I'm sorry I don't get it. What do you mean the preview server and launch buttons are?

**Comment by fire** [comment]
The top right of the godot editor has launch game, launch scene and launch html.

**Comment by mununki** [comment]
Wow, it pops up the brower and seems running the debug mode which has URL `http://localhost:8060/tmp_js_export.html`. How can I actually export it? I can't press the right click or go into inspect mode to figure it out.

**Comment by mununki** [comment]
I works! I don't know why. But it starts exporting the web output including *.js and *.wasm files since I pressed the preview server as you mentioned. Is it pre-condition to export the web project in order?

Anyway, I'm so happy to be able to use the json assets in my project and export it to outputs. I really appreciate your help! ❤️👍
